C99e99s61 understanding encapsulations polymorphisms in java
pawan-malhotra/blogs-converteasly pull request #5
Opened 2024-03-02 06:30 UTC by shubham9345

2024-03-02 18:52 UTC, pawan-malhotra requested changes

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +date: '27 february, 2024'
keep first letter of month in capital and change the format to month date, year (February 27, 2024)

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +sub_heading: "Let's dive into the concept of Encapsulation and Polymorphism more deeply with a lots of examples"
update sub_heading with 'Encapsulation is a fundamental principle in object-oriented programming (OOP) where the internal state of an object is hidden from outside access.'. sub_heading should be the part of blog.

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +Encapsulation is a process of binding the class of memeber into a single unit.It protects the data of class to be accessed from outside the class.However it is accessed outside the class by using acc
provide space before However

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +     @Override
provide space before override annotation

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// Main.java
provide space before line 60

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// Subclass of Animal
provide space after line 100

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// subclass of Animal
provide space after line 107

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// Main.java
give space after line 114

2024-03-02 18:52 UTC, pawan-malhotra commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +
update index count in readme.md file

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +date: '27 february, 2024'
done

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +sub_heading: "Let's dive into the concept of Encapsulation and Polymorphism more deeply with a lots of examples"
done

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +Encapsulation is a process of binding the class of memeber into a single unit.It protects the data of class to be accessed from outside the class.However it is accessed outside the class by using acc
done

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +     @Override
done

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// Main.java
done

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// Subclass of Animal
done

2024-03-05 18:41 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// subclass of Animal
done

2024-03-05 18:42 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +// Main.java
done

2024-03-05 18:42 UTC, shubham9345 commented on general/c99e99s61_understanding_encapsulation_and_polymorphism_in_java.md
> +
done

2024-03-06 18:46 UTC, pawan-malhotra approved these changes

2024-03-07 06:03 UTC, merged